# Generated by Django 5.2.5 on 2025-09-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_city_country_city_abrev_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_city',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id_country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
