# Generated by Django 5.2.5 on 2025-09-08 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.city'),
        ),
    ]
