# Generated by Django 5.2.5 on 2025-09-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_id_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='id_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.country'),
        ),
    ]
